### ISSUE TITLE
Add filtering based on UN subregions

### ISSUE THREAD

**Issue by HimanshuRanka** [PathoTracker/Pathotracker#116]
We want to add a filter that will allow users to filter on WHO subregions as well. Similar to WHO region when a subregion is selected we want the map to zoom in on that subregion. 

We want to make the subregion filter responsive to changes in the WHO region and country filters and vice versa.
- i.e. If we select a specific country, then the other 2 dropdowns only show options in which that country belong etc. Ask me for more details if confused. 

This should be additive. i.e. if multiple regions are selected the map zoom should include all the selected regions. 

https://www.google.com/url?q=https://unstats.un.org/unsd/methodology/m49/&sa=D&source=docs&ust=1704240536012873&usg=AOvVaw0kjgxUQNJsRAAgnRGNTTdG

**Comment by SeanKennyNF** [comment]
> We want to make the subregion filter responsive to changes in the WHO region and country filters and vice versa.
> i.e. If we select a specific country, then the other 2 dropdowns only show options in which that country belong etc. Ask me for more details if confused.

My thoughts here would be to change the logic with the region filters. (Ex. selecting "India" and "Eastern Europe" means "Please get me all estimates for India or Eastern Europe" instead of "Please get me all Indian estimates in Eastern Europe (non-existent)". I get that your suggestion is a quality of life thing for the users but my one reservation is that selecting a specific country or WHO region in addition to a UN region becomes impossible.

Left a similar comment here: https://github.com/PathoTracker/Pathotracker/pull/127#discussion_r1450851256

Would you be open to trying a version of the filters like what I am describing instead of reducing the number of countries visible?

I'm going to move this ticket to ready for review because everything except for this requirement is in PR but I think this requirement needs a bit more discussion + should be a separate ticket since I think we should give WHO region the same treatment.

Anyways, let me know what you think!
